### PR TITLE
Wire Complete implementation of Issue #2923 todos

### LINKED ISSUE #2923: Wire todos (help needed)
Hi, Wire feature needs to be finished ( twitter clone in rs)
we need little help with it, to make rs wire useable

Done ✔:
✔ Auto update Wire Service with RsEvent 
✔ Edit Profile/Account
✔ Mast Head Background Image

Issues:
- Follower notify does not work
- Wire Posts not shown in WireNotifyPostItem (maybe bug)
- WirePostItem.cpp class( new feed Version but not working yet)
- Notify Replies & Reposts too (ui not done yet)

Todos:
-> Notify for Wire Replies/republishes,& likes)
-> Home/Main Button for View the new Tweets from all users(which im following)
-> Search filter for users (not easy to look for a username to find)
-> Follower count
-> Sort users by Activity
-> RS links for posts/replies& profiles (partialy done on gui not)
-> Filter profiles feature ( not show dead accounts/outdated users)
-> Edit Wire Sync ( seems it doesnt gets more old wire posts) via context set (store posts/ sync posts)
-> Edit posts feature
-> Wire Groups Stats for Profiles -> Pulses, Replies, Republishes, Likes (seems not done yet in /libretroshare/services/p3wire.cc)

Any time later todo:
-> #hashtags
-> @mentions & notify mentions
-> Each Wire Account seperated follower/following list
-> Add Api for webui (retroshare/rswire.h)

any help is here welcome -> https://github.com/RetroShare/RetroShare/pull/3068

Actually like Wire feature in retroshare

Image

Image

Source path:
libretroshare/service:
https://github.com/RetroShare/libretroshare/blob/master/src/services/p3wire.cc
https://github.com/RetroShare/libretroshare/blob/master/src/services/p3wire.h

rsitems:
https://github.com/RetroShare/libretroshare/blob/master/src/rsitems/rswireitems.cc
https://github.com/RetroShare/libretroshare/blob/master/src/rsitems/rswireitems.h

Interface:
https://github.com/RetroShare/libretroshare/blob/master/src/retroshare/rswire.h

Gui Part:
https://github.com/RetroShare/RetroShare/tree/master/retroshare-gui/src/gui/TheWire

enable wire for compile:
`CONFIG += gxsthewire
`

```
$ cd retroshare
$ qmake
$ make
```

Howto compile:
Linux:
[Linux_InstallGuide.md](https://github.com/RetroShare/RetroShare/blob/master/build_scripts/Debian+Ubuntu/Linux_InstallGuide.md
)
Windows:
[WindowsMSys2_InstallGuide.md](https://github.com/RetroShare/RetroShare/blob/master/build_scripts/Windows-msys2/WindowsMSys2_InstallGuide.md
)
MacOS
[MacOS_X_InstallGuide.md](https://github.com/RetroShare/RetroShare/blob/master/build_scripts/OSX/MacOS_X_InstallGuide.md)

To Edit or Create Ui files you can use Qt Creator or Qt Designer

### PR DESCRIPTION
**Pull request by SaurabhCodesAI**
Implements Wire feature todos from #2923:

- Enabled NEW_REPLY, NEW_REPUBLISH, NEW_LIKE handlers in NewsFeed
- Fixed WireNotifyPostItem to use getWirePulse()
- Added Home button, search filter, sort, hide inactive in WireDialog
- Added Copy Link for pulses and profiles
- Added Following count display
- Enabled FOLLOW_STATUS_CHANGED event

Fixes #2923

### CODE REVIEW

**Comment by defnax** [comment]
you added to much widgets 
image
only one search line was more nice

**Comment by SaurabhCodesAI** [comment]
> you added to much widgets image only one search line was more nice

Done i removed the extra widgets.

**Comment by defnax** [comment]
Maybe by mistake you hided (All/Following/ combo box)

**Comment by defnax** [comment]
remove this line 81 //ui.comboBox_groupSet->hide();
we cant switch more to all or back

**Comment by SaurabhCodesAI** [comment]
Okay, I will take a look at it when I will be back from vacation...

**Comment by defnax** [comment]
@csoler please review

**Comment by defnax** [comment]
@csoler please review

File: retroshare-gui/src/gui/feeds/WireNotifyPostItem.cpp [hunk 1]
```diff
@@ -0,0 +1,786 @@
...
+    });
+}
+
+void WireNotifyPostItem::loadComment()
+{
+#ifdef DEBUG_ITEM
+    std::cerr << "WireNotifyPostItem::loadComment()";
+    std::cerr << std::endl;
+#endif
+//    mLoadingComment = true;
```
Comment (csoler) [inline retroshare-gui/src/gui/feeds/WireNotifyPostItem.cpp]: Is that work in progress?

File: retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.cpp [hunk 2]
```diff
@@ -173,7 +172,7 @@ void GxsGroupFrameDialog::initUi()
 	processSettings(true);
 
 	if (groupFrameSettingsType() != GroupFrameSettings::Nothing) {
-        connect(RsGUIEventManager::getInstance(), SIGNAL(settingsChanged()), this, SLOT(settingsChanged()));
+		//connect(NotifyQt::getInstance(), SIGNAL(settingsChanged()), this, SLOT(settingsChanged()));
```
Comment (csoler) [inline retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.cpp]: UIEventManager is the new one, NotifyQt is the deprecated (removed) one.

File: retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.h [hunk 3]
```diff
@@ -44,7 +45,7 @@ class UIStateHelper;
 struct RsGxsCommentService;
 class GxsCommentDialog;
 
-class GxsGroupFrameDialog : public MainPage
+class GxsGroupFrameDialog : public GxsStatisticsProvider
```
Comment (csoler) [inline retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.h]: you may use multiple inheritance here if you want to add some functionality from GxsStatisticsProvider while still deriving from MainPage. Still, I find this change surprising because it affects all services, not only wire.

File: retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.h [hunk 4]
```diff
@@ -186,53 +182,44 @@ private slots:
...
+
 	RsGxsGroupId mGroupId;
-	RsGxsIfaceHelper *mInterface;
 
 	QTreeWidgetItem *mYourGroups;
 	QTreeWidgetItem *mSubscribedGroups;
 	QTreeWidgetItem *mPopularGroups;
 	QTreeWidgetItem *mOtherGroups;
 
-	RsGxsGroupId mNavigatePendingGroupId;
```
Comment (csoler) [inline retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.h:216]: This is used in many services. Why remove it?

File: retroshare-gui/src/gui/gxs/GxsStatisticsProvider.h [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+class GxsStatisticsProvider  : public MainPage
+{
+    Q_OBJECT
+
+public:
+    GxsStatisticsProvider(RsGxsIfaceHelper *ifaceImpl, const QString& settings_name,QWidget *parent = 0,bool allow_dist_sync=false);
+    virtual ~GxsStatisticsProvider();
+
+    virtual void getServiceStatistics(GxsServiceStatistic& stats) const = 0;
+    virtual bool navigate(const RsGxsGroupId &groupId, const RsGxsMessageId& msgId) = 0;
```
Comment (csoler) [inline retroshare-gui/src/gui/gxs/GxsStatisticsProvider.h]: this should stay in MainPage. It's not really relevant here.

File: retroshare-gui/src/gui/gxs/GxsUserNotify.cpp [hunk 6]
```diff
@@ -26,7 +26,7 @@
 
 #define TOKEN_TYPE_STATISTICS  1
 
-GxsUserNotify::GxsUserNotify(RsGxsIfaceHelper */*ifaceImpl*/, const GxsGroupFrameDialog *g,QObject *parent) : UserNotify(parent), mGroupFrameDialog(g)
+GxsUserNotify::GxsUserNotify(RsGxsIfaceHelper */*ifaceImpl*/, const GxsStatisticsProvider *g,QObject *parent) : UserNotify(parent), mGxsStatisticsProvider(g)
```
Comment (csoler) [inline retroshare-gui/src/gui/gxs/GxsUserNotify.cpp:29]: ok, I see now why you did this. I think that you really should use multiple inheritance.

File: retroshare-gui/src/gui/TheWire/PulseAddDialog.cpp [hunk 7]
```diff
@@ -269,12 +282,14 @@ void PulseAddDialog::setReplyTo(const RsGxsGroupId &grpId, const RsGxsMessageId
         if(!rsWire->getWireGroup(grpId,pGroup))
         {
             std::cerr << __PRETTY_FUNCTION__ << "PulseAddDialog::setRplyTo() failed to fetch group id: "  << grpId << std::endl;
+            RsQThreadUtils::postToObject([this]() { hide(); }, this);
```
Comment (csoler) [inline retroshare-gui/src/gui/TheWire/PulseAddDialog.cpp:285]: you load the group but you do nothing with it?

**Review by csoler — COMMENTED** [review]
- the loading mechanism for the WireNotifyGroupItem and WireNotifyPostItem is the wrong one (actually the old one): done this way, when the db is not ready (or overloaded) it may exceed the request timeout and your item stays empty forever in loading state, meaning that it takes a long time to disapear when clearing the feed list. See how we did it for other items: there is a set of variables for each async element that needs to be loaded and the item is updated when all the data is present. Good example to follow: GxsChannelPostItem.cpp. You will see that it's not a big change to your code, but it's essential to make it react like other feed items.
- what is the role of the NotifyWidget class? If not used, removed it.
- WirePostItem and WireNotifyPostItem are doing the same thing? If so, remove the extra class.

File: retroshare-gui/src/gui/feeds/WireNotifyPostItem.cpp (hunk 1 above)
Comment (SaurabhCodesAI) [reply retroshare-gui/src/gui/feeds/WireNotifyPostItem.cpp]: yes, Wire has no comment support yet

File: retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.cpp (hunk 2 above)
Comment (SaurabhCodesAI) [reply retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.cpp]: done, restored RsGUIEventManager::getInstance() and its include

File: retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.h (hunk 3 above)
Comment (SaurabhCodesAI) [reply retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.h]: done now no behavioral change for other services.

File: retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.h (hunk 4 above)
Comment (SaurabhCodesAI) [reply retroshare-gui/src/gui/gxs/GxsGroupFrameDialog.h:216]: i restored It was moved to GxsStatisticsProvider by mistake

File: retroshare-gui/src/gui/gxs/GxsStatisticsProvider.h (hunk 5 above)
Comment (SaurabhCodesAI) [reply retroshare-gui/src/gui/gxs/GxsStatisticsProvider.h]: okay removed

File: retroshare-gui/src/gui/gxs/GxsUserNotify.cpp (hunk 6 above)
Comment (SaurabhCodesAI) [reply retroshare-gui/src/gui/gxs/GxsUserNotify.cpp:29]: done now uses multiple inheritance GxsUserNotify takes const GxsStatisticsProvider* and works for both.

File: retroshare-gui/src/gui/TheWire/PulseAddDialog.cpp (hunk 7 above)
Comment (SaurabhCodesAI) [reply retroshare-gui/src/gui/TheWire/PulseAddDialog.cpp:285]: It wasn't intentional, it was just missed The group was loaded, used for the UI but the assignment to mGroup was forgotten

**Comment by SaurabhCodesAI** [comment]
@csoler can you review again please, i fixed the changes you mentioned let me know if any more things to change...

File: retroshare-gui/src/gui/feeds/WireNotifyPostItem.h [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+class WireNotifyPostItem : public GxsFeedItem
+{
+    Q_OBJECT
+
+public:
+    // This one is used in NewFeed for incoming Wire posts. Only the group and msg ids are known at this point.
+    // It can be used for all apparences of wire posts. But in rder to merge comments from the previous versions of the post, the list of
+    // previous posts should be supplied. It's optional. If not supplied only the comments of the new version will be displayed.
+    WireNotifyPostItem(FeedHolder *feedHolder, uint32_t feedId, const RsGxsGroupId& groupId, const RsGxsMessageId &messageId, bool isHome, bool autoUpdate, const std::set<RsGxsMessageId>& older_versions = std::set<RsGxsMessageId>());
+    WireNotifyPostItem(FeedHolder *parent, uint32_t feedId, const RsGroupMetaData& group_meta, const RsGxsMessageId& messageId, bool isHome, bool autoUpdate, const std::set<RsGxsMessageId>& older_versions = std::set<RsGxsMessageId>());
```
Comment (csoler) [inline retroshare-gui/src/gui/feeds/WireNotifyPostItem.h]: Is this one actually used? A while ago, feed items where also used by some services to display their data in the service tab, which explains that we had two different constructors. I suppose that Wire doesn't do that (or does it?). The IsHome bool is some dead feature also related to that.  When isHome=true that meant the feed item was actually used to show data in the service tab. This is why you see in fill() the if(mIsHome) {...} that shows some more stuff. In feeds this can be removed. As you can see whenever a new item is created (see NewsFeed.cpp:506 and 265), we use false for mIsHome. It's up to you to remove this in WireNotifyPostItem. That old code is still there in every feed item type.

File: retroshare-gui/src/gui/TheWire/WireDialog.h [hunk 9]
```diff
@@ -68,7 +72,7 @@ class WireViewHistory
 };
 //---------------------------------------------------------
 
-class WireDialog : public MainPage, public TokenResponse, public WireGroupHolder, public PulseViewHolder
+class WireDialog : public MainPage, public GxsStatisticsProvider, public TokenResponse, public WireGroupHolder, public PulseViewHolder
```
Comment (csoler) [inline retroshare-gui/src/gui/TheWire/WireDialog.h]: No need to derive from TokenResponse since everything should use the sync API in rsWire.

**Review by csoler — COMMENTED** [review]
almost there!

**Comment by SaurabhCodesAI** [comment]
> almost there!

All items from your review are fixed and verified
